%% ERP measurement script 


% get peak value 
% 'peakampbl'
ALLERP = pop_geterpvalues( ERP, [ 100 400],  26,  1:64 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_peakvalue_1.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peakampbl', 'Neighborhood',  3,...
 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

ALLERP = pop_geterpvalues( ERP, [ 100 400],  28,  1:64 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_peakvalue_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peakampbl', 'Neighborhood',  3,...
 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

ALLERP = pop_geterpvalues( ERP, [ 100 400],  30,  1:64 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_peakvalue_3.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peakampbl', 'Neighborhood',  3,...
 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );


% get peak latency
% 'peaklatbl'
LLERP = pop_geterpvalues( ALLERP, [ 100 400],  41,  1:64 , 'Baseline', 'pre', 'Erpsets',  2, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_peakvalue_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'Neighborhood',...
  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );


%% plot area 
%standard valid 1
ALLERP = pop_geterpvalues( ERP, [ 203 503],  25,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_valid_area_1.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%standard valid 2
ALLERP = pop_geterpvalues( ERP, [ 203 503],  27,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_valid_area_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%standard valid 3
ALLERP = pop_geterpvalues( ERP, [ 203 503],  29,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_valid_area_3.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%standard invalid 1
ALLERP = pop_geterpvalues( ERP, [ 300 600],  26,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_area_1.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%standard invalid 2
ALLERP = pop_geterpvalues( ERP, [ 300 600],  28,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_area_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%standard invalid 3
ALLERP = pop_geterpvalues( ERP, [ 300 600],  30,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_area_3.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );




% control
%control valid 1
ALLERP = pop_geterpvalues( ERP, [ 212 512],  39,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_area_1.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%Control valid 2
ALLERP = pop_geterpvalues( ERP, [ 212 512],  41,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_area_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%Control valid 3
ALLERP = pop_geterpvalues( ERP, [ 212 512],  43,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_area_3.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );


%control invalid 1
ALLERP = pop_geterpvalues( ERP, [ 283 583],  40,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_area_1.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%Control invalid 2
ALLERP = pop_geterpvalues( ERP, [ 283 583],  42,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_area_2.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );

%Control invalid 3
ALLERP = pop_geterpvalues( ERP, [ 283 583],  44,  62 , 'Baseline', 'pre', 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_area_3.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'areat', 'Resolution',...
  3 );







%% %%%%%%%%%%
% get peak amplitude from one to six, in both hemispheres
% valid
ALLERP = pop_geterpvalues( ALLERP, [ 100 400],  25:2:35, [ 1 2] , 'Baseline', 'pre', 'Erpsets',  2, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_valid_peakvalue_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peakampbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

% peak latency
ALLERP = pop_geterpvalues( ALLERP, [ 100 400],  25:2:35, [ 1 2] , 'Baseline', 'pre', 'Erpsets',  2, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_valid_peaklatency_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );


%% invalid
% aamplitude
ALLERP = pop_geterpvalues( ALLERP, [ 150 400],  26:2:36, [ 1 2] , 'Baseline', 'pre', 'Erpsets',  2, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_peakvalue_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peakampbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

% latency
ALLERP = pop_geterpvalues( ALLERP, [ 150 400],  26:2:36, [ 1 2] , 'Baseline', 'pre', 'Erpsets',  2, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Standard_invalid_peaklatency_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );



%% load control
ERP = pop_loaderp( 'filename', 'JD18Jan17_control.erp', 'filepath', '/Users/jdf/Dropbox/' );
% add bins
ERP = pop_binoperator( ERP, {  'b45 = (b39 + b41 + b43) / 3 label valid 1-3',  'b46 = (b40 + b42 + b44) / 3 label invalid 1-3',...
  'b47 = (b13 + b14) / 2 label valid 4',  'b48 = (b15 + b16) / 2 label invalid 4',  'b49 = (b17 + b18) / 2 label valid 5',  'b50 = (b19 + b20) / 2 label invalid 5',...
  'b51 = (b21 + b22) / 2 label valid 6',  'b52 = (b23 + b24) / 2 label invalid 6'});
% two hemispheres
ERP = pop_erpchanoperator( ERP, {  'nch1 = avgchan(16:26) label ROI-Left',  'nch2 = avgchan(53:64) label RIO-Right'} , 'ErrorMsg', 'popup',...
 'Warning', 'on' );


%% get peak amplitude

% valid
ALLERP = pop_geterpvalues( ALLERP, [ 100 400], [ 39:2:43 47:2:51], [ 1 2] , 'Baseline', 'pre', 'Erpsets',  4, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_peakvalue_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peakampbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

% peak latency
ALLERP = pop_geterpvalues( ALLERP, [ 100 400], [ 39:2:43 47:2:51], [ 1 2] , 'Baseline', 'pre', 'Erpsets',  4, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_valid_peaklatency_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure',...
 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

%% invalid
ALLERP = pop_geterpvalues( ALLERP, [ 100 400], [ 40:2:44 48:2:52], [ 1 2] , 'Baseline', 'pre', 'Erpsets',  4, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_peakvalue_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'peakampbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );

ALLERP = pop_geterpvalues( ALLERP, [ 100 400], [ 40:2:44 48:2:52], [ 1 2] , 'Baseline', 'pre', 'Erpsets',  4, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_peaklatency_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );





ALLERP = pop_geterpvalues( ALLERP, [ 100 400], [ 40:2:44 48:2:52], [ 1 2] , 'Baseline', 'pre', 'Erpsets',  4, 'FileFormat', 'long', 'Filename',...
 '/Users/jdf/Dropbox/Chen_PhD/Experiment1a_eeg/Control_invalid_peaklatency_twoSides_1-6.txt', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'peaklatbl', 'Neighborhood',  3, 'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution',  3 );





